{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "dchat.fullname" . }}
  labels:
    {{- include "dchat.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "dchat.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow ingress from ALB/ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.networkPolicy.ingressNamespace }}
      ports:
        - protocol: TCP
          port: 7070
    # Allow ingress from Prometheus
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.networkPolicy.monitoringNamespace }}
      ports:
        - protocol: TCP
          port: 9090
    # Allow ingress from other dchat pods (peer-to-peer)
    - from:
        - podSelector:
            matchLabels:
              {{- include "dchat.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 7070
  egress:
    # Allow DNS
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
      ports:
        - protocol: UDP
          port: 53
    # Allow database access
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              app: postgresql
      ports:
        - protocol: TCP
          port: 5432
    # Allow chain RPC access (external)
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
    # Allow peer-to-peer communication
    - to:
        - podSelector:
            matchLabels:
              {{- include "dchat.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 7070
    {{- with .Values.networkPolicy.extraEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
