apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dchat.fullname" . }}-db
  labels:
    {{- include "dchat.labels" . | nindent 4 }}
type: Opaque
stringData:
  host: {{ .Values.database.host | quote }}
  port: {{ .Values.database.port | quote }}
  database: {{ .Values.database.name | quote }}
  username: {{ .Values.database.username | quote }}
  password: {{ .Values.database.password | quote }}
