apiVersion: v1
kind: Service
metadata:
  name: {{ include "dchat.fullname" . }}
  labels:
    {{- include "dchat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: relay
      protocol: TCP
      name: relay
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "dchat.selectorLabels" . | nindent 4 }}
