# dchat Configuration File
# Copy this file to config.toml and modify as needed
# Environment variables can override these settings (prefix with DCHAT_)

[network]
# Addresses to listen on (multiaddr format)
# Default: Listen on all interfaces with random ports
listen_addresses = [
    "/ip4/0.0.0.0/tcp/7070",           # TCP on port 7070
    "/ip4/0.0.0.0/udp/7070/quic-v1"    # QUIC on port 7070
]

# Bootstrap peer addresses (multiaddr format with peer IDs)
# Example: ["/dns4/relay1.dchat.io/tcp/7070/p2p/12D3KooWExample..."]
bootstrap_peers = []

# Maximum number of simultaneous connections
# Default: 100 (increase for relay nodes)
max_connections = 100

# Connection timeout in milliseconds
# Default: 10000 (10 seconds)
connection_timeout_ms = 10000

# Enable mDNS for local peer discovery
# Default: true (disable in production)
enable_mdns = true

# Enable UPnP for automatic port forwarding
# Default: true (works on most home routers)
enable_upnp = true

[storage]
# Directory for storing application data
# Default: ./dchat_data
data_dir = "./dchat_data"

# Maximum number of messages to cache in memory
# Default: 10000
max_message_cache_size = 10000

# Number of days to retain messages
# Default: 30 (0 = forever)
message_retention_days = 30

# Enable automatic backups
# Default: true
enable_backup = true

# Backup interval in hours
# Default: 24 (daily backups)
backup_interval_hours = 24

# Database connection pool size
# Higher values support more concurrent operations but use more memory
# Default: 10
db_pool_size = 10

# Connection acquisition timeout in seconds
# How long to wait for an available connection before failing
# Default: 30
db_connection_timeout_secs = 30

# Idle connection timeout in seconds
# Connections idle longer than this are closed (600s = 10 minutes)
# Default: 600
db_idle_timeout_secs = 600

# Maximum connection lifetime in seconds
# Connections older than this are recycled (1800s = 30 minutes)
# Default: 1800
db_max_lifetime_secs = 1800

# Enable Write-Ahead Logging for better concurrency
# WAL mode allows concurrent reads and writes
# Default: true
db_enable_wal = true

[crypto]
# Key rotation interval in hours
# Default: 168 (1 week)
key_rotation_interval_hours = 168

# Maximum messages before key rotation
# Default: 10000
max_messages_per_key = 10000

# Enable post-quantum cryptography (experimental)
# Default: false (set true for quantum resistance)
enable_post_quantum = false

# Noise protocol pattern
# Default: Noise_XX_25519_ChaChaPoly_BLAKE2s
# Options: Noise_XX_25519_ChaChaPoly_BLAKE2s, Noise_IK_25519_ChaChaPoly_BLAKE2s
noise_protocol_pattern = "Noise_XX_25519_ChaChaPoly_BLAKE2s"

[governance]
# Voting period duration in hours
# Default: 168 (1 week)
voting_period_hours = 168

# Minimum stake required to create a proposal
# Default: 1000
minimum_stake_for_proposal = 1000

# Quorum threshold (0.0 to 1.0)
# Default: 0.1 (10% of total stake must vote)
quorum_threshold = 0.1

# Enable anonymous voting with zero-knowledge proofs
# Default: true
enable_anonymous_voting = true

[relay]
# Enable relay mode (routes messages between peers)
# Default: false (set true for relay nodes)
enable_relay = false

# Maximum relay connections (only if relay enabled)
# Default: 50 (increase for high-capacity relays)
max_relay_connections = 50

# Reward threshold for relay services
# Default: 100
relay_reward_threshold = 100

# Uptime reporting interval in minutes
# Default: 60 (report every hour)
uptime_reporting_interval_minutes = 60

# Stake amount for relay node registration
# Default: 5000
stake_amount = 5000

# Environment Variable Overrides:
# DCHAT_LISTEN_ADDR - Override listen addresses (comma-separated)
# DCHAT_BOOTSTRAP_PEERS - Override bootstrap peers (comma-separated)
# DCHAT_DATA_DIR - Override data directory path
# DCHAT_MAX_CONNECTIONS - Override max connections
#
# Example:
# DCHAT_LISTEN_ADDR="/ip4/0.0.0.0/tcp/7070" dchat relay
