# cargo-deny configuration
# https://github.com/EmbarkStudios/cargo-deny

# Note: This configuration is for cargo-deny 0.14+
# See: https://embarkstudios.github.io/cargo-deny/

[graph]
targets = []
all-features = true

[output]
feature-depth = 1

[advisories]
ignore = [
    "RUSTSEC-2025-0009",  # ring 0.16.20 - via libp2p-tls (unused feature)
    "RUSTSEC-2023-0071",  # rsa 0.9.8 - via sqlx-mysql (unused backend)  
    "RUSTSEC-2024-0384",  # instant unmaintained - via libp2p (waiting for update)
    "RUSTSEC-2024-0436",  # paste unmaintained - build-time only
    "RUSTSEC-2025-0010",  # ring 0.16.20 unmaintained - via libp2p-tls
]

[licenses]
# Allow only specific licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "MPL-2.0",           # Mozilla Public License (webpki-roots)
    "Unicode-3.0",       # Unicode License (ICU crates)
]

# Skip license checks for workspace crates (our own code)
[licenses.private]
ignore = true
# Allow workspace members without licenses during development
registries = []

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"

# NOTE: We don't ban sha1/md5 here because they're used by some dependencies
# for non-cryptographic purposes (e.g., git hashing). We don't use them directly.

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
