apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: dchat-alerts
  namespace: monitoring
  labels:
    app: dchat
    prometheus: monitoring
spec:
  groups:
    - name: dchat.application
      interval: 30s
      rules:
        # High error rate
        - alert: DchatHighErrorRate
          expr: |
            (
              sum(rate(dchat_errors_total[5m])) by (instance)
              /
              sum(rate(dchat_requests_total[5m])) by (instance)
            ) > 0.01
          for: 5m
          labels:
            severity: critical
            component: application
          annotations:
            summary: "High error rate detected on {{ $labels.instance }}"
            description: "Error rate is {{ $value | humanizePercentage }} (threshold: 1%)"
            runbook_url: "https://docs.dchat.example.com/runbooks/high-error-rate"
        
        # High message latency
        - alert: DchatHighLatency
          expr: |
            histogram_quantile(0.95,
              sum(rate(dchat_message_latency_seconds_bucket[5m])) by (le, instance)
            ) > 0.5
          for: 10m
          labels:
            severity: high
            component: messaging
          annotations:
            summary: "High message latency on {{ $labels.instance }}"
            description: "P95 latency is {{ $value | humanizeDuration }} (threshold: 500ms)"
            runbook_url: "https://docs.dchat.example.com/runbooks/high-latency"
        
        # Low relay throughput
        - alert: DchatLowThroughput
          expr: |
            sum(rate(dchat_messages_relayed_total[5m])) by (instance) < 10
          for: 15m
          labels:
            severity: warning
            component: relay
          annotations:
            summary: "Low message throughput on {{ $labels.instance }}"
            description: "Throughput is {{ $value | humanize }} msg/s (threshold: 10 msg/s)"
            runbook_url: "https://docs.dchat.example.com/runbooks/low-throughput"
        
        # Database connection pool exhaustion
        - alert: DchatDatabasePoolExhausted
          expr: |
            dchat_database_connections_active / dchat_database_connections_max > 0.8
          for: 5m
          labels:
            severity: high
            component: database
          annotations:
            summary: "Database connection pool near exhaustion"
            description: "Connection pool is {{ $value | humanizePercentage }} full (threshold: 80%)"
            runbook_url: "https://docs.dchat.example.com/runbooks/database-pool-exhausted"
        
        # Slow database queries
        - alert: DchatSlowDatabaseQueries
          expr: |
            histogram_quantile(0.95,
              sum(rate(dchat_database_query_duration_seconds_bucket[5m])) by (le, query)
            ) > 1.0
          for: 10m
          labels:
            severity: warning
            component: database
          annotations:
            summary: "Slow database queries detected"
            description: "P95 query duration for {{ $labels.query }} is {{ $value | humanizeDuration }} (threshold: 1s)"
            runbook_url: "https://docs.dchat.example.com/runbooks/slow-queries"
    
    - name: dchat.infrastructure
      interval: 30s
      rules:
        # Pod not ready
        - alert: DchatPodNotReady
          expr: |
            kube_pod_status_ready{
              namespace="default",
              condition="true",
              pod=~"dchat-.*"
            } == 0
          for: 5m
          labels:
            severity: high
            component: kubernetes
          annotations:
            summary: "Pod {{ $labels.pod }} is not ready"
            description: "Pod has been not ready for more than 5 minutes"
            runbook_url: "https://docs.dchat.example.com/runbooks/pod-not-ready"
        
        # High CPU usage
        - alert: DchatHighCPU
          expr: |
            sum(rate(container_cpu_usage_seconds_total{
              namespace="default",
              pod=~"dchat-.*"
            }[5m])) by (pod)
            /
            sum(kube_pod_container_resource_limits{
              namespace="default",
              pod=~"dchat-.*",
              resource="cpu"
            }) by (pod) > 0.8
          for: 10m
          labels:
            severity: warning
            component: resources
          annotations:
            summary: "High CPU usage on {{ $labels.pod }}"
            description: "CPU usage is {{ $value | humanizePercentage }} (threshold: 80%)"
            runbook_url: "https://docs.dchat.example.com/runbooks/high-cpu"
        
        # High memory usage
        - alert: DchatHighMemory
          expr: |
            sum(container_memory_working_set_bytes{
              namespace="default",
              pod=~"dchat-.*"
            }) by (pod)
            /
            sum(kube_pod_container_resource_limits{
              namespace="default",
              pod=~"dchat-.*",
              resource="memory"
            }) by (pod) > 0.9
          for: 5m
          labels:
            severity: critical
            component: resources
          annotations:
            summary: "High memory usage on {{ $labels.pod }}"
            description: "Memory usage is {{ $value | humanizePercentage }} (threshold: 90%)"
            runbook_url: "https://docs.dchat.example.com/runbooks/high-memory"
        
        # Persistent volume almost full
        - alert: DchatPVCAlmostFull
          expr: |
            kubelet_volume_stats_used_bytes{
              namespace="default",
              persistentvolumeclaim=~"dchat-.*"
            }
            /
            kubelet_volume_stats_capacity_bytes{
              namespace="default",
              persistentvolumeclaim=~"dchat-.*"
            } > 0.8
          for: 10m
          labels:
            severity: warning
            component: storage
          annotations:
            summary: "PVC {{ $labels.persistentvolumeclaim }} is almost full"
            description: "Volume is {{ $value | humanizePercentage }} full (threshold: 80%)"
            runbook_url: "https://docs.dchat.example.com/runbooks/pvc-almost-full"
        
        # Too many pod restarts
        - alert: DchatPodRestarting
          expr: |
            rate(kube_pod_container_status_restarts_total{
              namespace="default",
              pod=~"dchat-.*"
            }[15m]) > 0.1
          for: 5m
          labels:
            severity: warning
            component: kubernetes
          annotations:
            summary: "Pod {{ $labels.pod }} is restarting frequently"
            description: "Pod has restarted {{ $value | humanize }} times in the last 15 minutes"
            runbook_url: "https://docs.dchat.example.com/runbooks/pod-restarting"
    
    - name: dchat.relay
      interval: 30s
      rules:
        # Relay node down
        - alert: DchatRelayNodeDown
          expr: |
            up{job="dchat-relay"} == 0
          for: 2m
          labels:
            severity: critical
            component: relay
          annotations:
            summary: "Relay node {{ $labels.instance }} is down"
            description: "Relay node has been down for more than 2 minutes"
            runbook_url: "https://docs.dchat.example.com/runbooks/relay-node-down"
        
        # Low relay peer count
        - alert: DchatLowRelayPeers
          expr: |
            dchat_relay_peers_connected < 3
          for: 10m
          labels:
            severity: warning
            component: relay
          annotations:
            summary: "Relay node {{ $labels.instance }} has low peer count"
            description: "Connected peers: {{ $value | humanize }} (threshold: 3)"
            runbook_url: "https://docs.dchat.example.com/runbooks/low-relay-peers"
        
        # High relay message queue depth
        - alert: DchatHighRelayQueue
          expr: |
            dchat_relay_message_queue_depth > 1000
          for: 5m
          labels:
            severity: high
            component: relay
          annotations:
            summary: "High message queue depth on {{ $labels.instance }}"
            description: "Queue depth: {{ $value | humanize }} messages (threshold: 1000)"
            runbook_url: "https://docs.dchat.example.com/runbooks/high-relay-queue"
    
    - name: dchat.security
      interval: 30s
      rules:
        # High rate of authentication failures
        - alert: DchatHighAuthFailures
          expr: |
            sum(rate(dchat_auth_failures_total[5m])) by (instance) > 10
          for: 5m
          labels:
            severity: high
            component: security
          annotations:
            summary: "High authentication failure rate on {{ $labels.instance }}"
            description: "Auth failure rate: {{ $value | humanize }} failures/s (threshold: 10/s)"
            runbook_url: "https://docs.dchat.example.com/runbooks/high-auth-failures"
        
        # Certificate expiring soon
        - alert: DchatCertificateExpiringSoon
          expr: |
            (dchat_tls_certificate_expiry_seconds - time()) / 86400 < 30
          for: 1h
          labels:
            severity: warning
            component: security
          annotations:
            summary: "TLS certificate expiring soon"
            description: "Certificate expires in {{ $value | humanize }} days (threshold: 30 days)"
            runbook_url: "https://docs.dchat.example.com/runbooks/certificate-expiring"
