# dchat Relay 1 Configuration
# Bootstrap node - no peers required

[network]
listen_addresses = [
    "/ip4/0.0.0.0/tcp/7070",
    "/ip4/0.0.0.0/udp/7070/quic-v1"
]

# Bootstrap node - empty bootstrap peers
bootstrap_peers = []

max_connections = 200
connection_timeout_ms = 15000
enable_mdns = false
enable_upnp = true

[storage]
data_dir = "/var/lib/dchat/data"
max_message_cache_size = 50000
message_retention_days = 90
enable_backup = true
backup_interval_hours = 6

db_pool_size = 20
db_connection_timeout_secs = 30
db_idle_timeout_secs = 600
db_max_lifetime_secs = 1800
db_enable_wal = true

[crypto]
key_rotation_interval_hours = 168
max_messages_per_key = 10000
enable_post_quantum = false
noise_protocol_pattern = "Noise_XX_25519_ChaChaPoly_BLAKE2s"

[governance]
voting_period_hours = 168
minimum_stake_for_proposal = 1000
quorum_threshold = 0.1
enable_anonymous_voting = true

[relay]
enable_relay = true
max_relay_connections = 100
relay_reward_threshold = 100
uptime_reporting_interval_minutes = 10
stake_amount = 5000

[monitoring]
metrics_enabled = true
metrics_port = 9090

tracing_enabled = true
tracing_endpoint = "http://localhost:4317"

health_check_enabled = true
health_check_port = 8080

[logging]
level = "info"
format = "json"
