# dchat Relay Configuration
# Enables relay node functionality with proper network settings

[relay]
# Enable relay mode (routes messages between peers)
enable_relay = true

# Maximum relay connections
max_relay_connections = 500

# Bandwidth limit in bytes per second (1 GB/s - very high)
bandwidth_limit_bps = 1_000_000_000

# Reward threshold for relay services
relay_reward_threshold = 100

# Uptime reporting interval in minutes
uptime_report_interval_minutes = 60

[network]
# Enable mDNS for local peer discovery
enable_mdns = true

# Disable UPnP in Docker (often times out)
enable_upnp = false

# Disable STUN in Docker
enable_stun = false

# Connection settings
max_connections = 500
connection_timeout_ms = 30000

[storage]
# Data directory for relay state
data_dir = "/var/lib/dchat/data"

# Message settings
max_message_cache_size = 100000
message_retention_days = 30
enable_backup = true
backup_interval_hours = 12

# Database settings
db_pool_size = 20
db_connection_timeout_secs = 30
db_idle_timeout_secs = 600
db_max_lifetime_secs = 1800
db_enable_wal = true

[metrics]
# Prometheus metrics
metrics_enabled = true
metrics_port = 9090

# Tracing
tracing_enabled = true
jaeger_endpoint = "http://jaeger:16686"
