name: dchat_sdk
description: Flutter/Dart SDK for dchat decentralized chat platform
version: 0.1.0
homepage: https://dchat.network
repository: https://github.com/dchat/dchat

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  crypto: ^3.0.3
  uuid: ^4.0.0
  ed25519_edwards: ^0.3.1
  pointycastle: ^3.7.3
  convert: ^3.1.1

dev_dependencies:
  test: ^1.24.0
  mockito: ^5.4.0
  build_runner: ^2.4.0
